homepage: "https://github.com/cyberviser/Hancock"
language: python
vendor: "CyberViser"
primary_contact: "cyberviser@proton.me"
auto_ccs:
  - "security@cyberviser.ai"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
  - coverage
main_repo: "https://github.com/cyberviser/Hancock"
file_github_issue: true
